config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "products#index"

  resources :products, :memberships
  namespace :manage do
    resources :products, :productimages
    resources :users do
      member do
        get 'toggle_admin'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord

  validates :user_id, presence: true

  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :discount_price, presence: true
  validates_associated :productimages
  validates :price, numericality: { only_integer: true }
  validates :discount_price, numericality: { only_integer: true }

  has_many :productimages, dependent: :destroy

  def cover_image
    if !self.productimages.exists?
      return "/images/placeholder.jpg"
    else
      return self.productimages.order("created_at ASC").first.productpicture_url(:square)
    end
  end
end

app/models/productimage.rb
class Productimage < ApplicationRecord
  validates :product_id, :productpicture, presence: true

  mount_uploader :productpicture, ProductpictureUploader

  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord

  validates_associated :membership

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one :membership, :dependent => :destroy

  def is_admin
    return (self.admin == 1)
  end
  
  def admin_status_in_words
    if self.admin == 1
      return "Admin"
    else
      return "Normal user"
    end
  end

  def has_premium_membership
    return !self.membership.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def admin_only
    redirect_to root_path if !current_user.is_admin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.find_or_initialize_by(user_id: current_user.id)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to root_path, notice: 'You have purchased the premium membership successfully' }
      else
        format.html { render :new }
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @show_discount = current_user.has_premium_membership
  end

  def show
    @product = Product.find(params[:id])
    @show_discount = current_user.has_premium_membership
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dakota</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='notice-msg'>
      <div class='container'>
        <% if notice %> <p class='alert alert-info'><%= notice %></p> <% end %>
        <% if alert %> <p class='alert alert-danger'><%= alert %></p> <% end %>
      </div> <%# .container %>
    </div> <%# #notice-msg %>

    <% if user_signed_in? %>
      <div id='user-nav'>
        <div class='container'>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Dakota</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">

                <li class="nav-item active">
                  <%= link_to "Home", root_path, class: 'nav-link' %>
                </li>

                <% if current_user.is_admin %>
                  <li class="nav-item active">
                    <%= link_to "Manage panel", manage_products_path, class: 'nav-link' %>
                  </li>
                <% end %>

                <% if current_user.has_premium_membership %>
                  <li class="nav-item">
                    <span id='membership-status' class='badge badge-info'>Membership: Premium</span>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to 'Get premium membership', new_membership_path, class: 'btn btn-outline-success'  %>
                  </li>
                <% end %>

                <li class="nav-item">
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>


              </ul>
            </div>
          </nav>
        </div> <%# .container %>
      </div> <%# #user-nav %>

      
    <% end %>

    <%= yield %>

    
  </body>
</html>

app/views/memberships/new.html.erb
<div id='page-memberships-new'>
  <div class='container'>
    <%= form_with model: @membership, local: true do |form| %>
      <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

          <ul>
          <% @membership.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.submit "One-click purchase", class: 'btn btn-primary btn-large' %>

    <% end %>
  </div> <%# .container %>
</div> <%# #page-memberships-new %>

app/views/products/index.html.erb
<div id='page-products-index'>
  <div class='container'>
    <h1>All products</h1>
    <div id='products'>
      <div class='row'>
        <% @products.each do |product| %>
          <div class='col-6 col-lg-3'>
            <%= link_to product, class: 'link-product' do %>
              <%= image_tag product.cover_image, 
                id: "img-cover-product-#{product.id}", class: 'img-cover-product' %>
              <div class='product-content'>
                <div class='product-name'><%= product.name %></div>
                <div class='product-price'>
                  <% if @show_discount %>
                      <span class='discount-price'>$<%= product.discount_price %></span>
                  <% end %>
                  <span class='regular-price <%= 'cross-out' if @show_discount %>'>
                    $<%= product.price %>
                  </span>
                </div> <%# .product-price %>
              </div> <%# .product-content %>
            <% end %> <%# .link-product %>
          </div><%# .col-6 %>
        <% end %>
      </div> <%# .row %>
    </div> <%# #products %>

  </div> <%# .container %>
</div> <%# #page-products-index %>

app/views/products/show.html.erb
<div id='page-products-show'>
  <div class='container'>
    <%= link_to 'Show all products', products_path, class: 'btn btn-light' %>

    <h1><%= @product.name %></h1>

    <div id='product-price'>
      <% if @show_discount %>
        <span id='discount-price'>$<%= @product.discount_price %></span>
      <% end %>

      <span id='regular-price' class="<%= 'cross-out' if @show_discount %>">$<%= @product.price %></span>
    </div> <%# #product-price %>

    <div id='productpictures'>
      <% unless @product.productimages.empty? %>
        <div class='row'>
          <% @product.productimages.each do |productimage| %>
            <div class='col-12 col-sm-6 col-lg-4'>
              <%= image_tag productimage.productpicture_url(:square) %>
            </div>
          <% end %>
        </div>
      <% else %>
        <%= image_tag "/images/placeholder.jpg", id: 'img-placeholder' %>
      <% end %>
    </div> <%# #productpictures %>

  </div> <%# .container %>
</div> <%# #page-products-show %>